---
title: 'Steven Maharaj 695281 Assignment 2, Question 3 MAST90125: Bayesian Statistical Learning'
header-includes:
   - \usepackage{bm}
   - \usepackage{amsmath}
output: 
  pdf_document:
    number_sections: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Due: Friday 20 September 2019**  
\vspace{5 mm}

**There are places in this assignment where R code will be required. Therefore set the random seed so assignment is reproducible.**

```{r}
set.seed(695281)#Please change random seed to your student id number.
library(dplyr)
library(tidyr)
library(ggplot2)
library(TruncatedNormal)
```

---
PART A


```{r}
Contraceptionsubset <- read.csv("Contraceptionsubset.csv")
```

---

Part B

Case $x \in (0,\infty)$
```{r}
mu = 0.5
sigma =  1 # sigma

a <- 0
b <- 10 # A number going to infinity
n <- 5000

invtn <- function(n,mu,sigma,a,b){
  u <- runif(n)
  return(qnorm(pnorm(a)+u*(pnorm(b) - pnorm(a)))*sigma + mu)
}

# Using my inverse cdf method
x_empircal <- invtn(n,mu,sigma,a,b)

# using the TruncatedNormal package 
x_empircal <- rtnorm(n = n, mu = mu, lb = a, ub = b, method = "fast")
empircal_den <- density(x_empircal)

x <- seq(a,b,length.out = n)
y <- dnorm(empircal_den$x,mean=mu,sd=sigma)/(pnorm(b,mean=mu,sd=sigma)-pnorm(a,mean=mu,sd=sigma))

plot(empircal_den$x,empircal_den$y,
main="Comparing densities for modified inverse CDF method",
ylab="Density",
xlab = "x",
type="l",
col="blue")
lines(empircal_den$x, y, col="red")
legend("topright",
c("Empirical","True"),
fill=c("blue","red")
)

```



Case $x \in (-\infty,0)$
```{r}
mu = 0.5
sigma =  1 # sigma

a <- -10
b <- 0 # A number going to infinity
n <- 5000


# Using my inverse cdf method
x_empircal <- invtn(n,mu,sigma,a,b)

# using the TruncatedNormal package 
x_empircal <- rtnorm(n = n, mu = mu, lb = a, ub = b, method = "fast")

empircal_den <- density(x_empircal)

x <- seq(a,b,length.out = n)

y <- dnorm(empircal_den$x,mean=mu,sd=sigma)/(pnorm(b,mean=mu,sd=sigma)-pnorm(a,mean=mu,sd=sigma))

plot(empircal_den$x,empircal_den$y,
main="Comparing densities for modified inverse CDF method",
ylab="Density",
xlab = "x",
type="l",
col="blue")
lines(empircal_den$x, y, col="red")
legend("topleft",
c("Empirical","True"),
fill=c("blue","red")
)

```


```{r}
library(TruncatedNormal)
rtnorm(n = 10, mu = 2, lb = 1:10, ub = 2:11, method = "fast")```


